import type { FieldDef } from "./types";

export const WEEKDAYS = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"] as const;
export const GAP_DIRS = ["up", "down", "none"] as const;
export const GAP_BUCKETS = ["xs", "s", "m", "l", "xl"] as const;
export const IB_BREAKS = ["none", "single_up", "single_down", "double"] as const;

/*
  Gap-size buckets (percent of prior close, absolute):
  xs < 0.15 ≤ s < 0.30 ≤ m < 0.75 ≤ l < 1.50 ≤ xl
*/

export const fields: FieldDef[] = [
  {
    kind: "field",
    name: "dayOfWeek",
    title: "Day of week",
    doc: "Weekday of the session's trade date (Mon–Sun). The classic seasonality cut: any query can be grouped or filtered by it.",
    valueType: "enum",
    enumValues: WEEKDAYS,
    sql: "f.dow",
    groupable: true,
    examples: ["gapFill WHERE dayOfWeek = Tue", "closeGreen GROUP BY dayOfWeek"],
    library: [
      { kind: "indicator", slug: "seasonality-widget" },
      { kind: "indicator", slug: "asset-class-seasonality" },
    ],
  },
  {
    kind: "field",
    name: "month",
    title: "Month",
    doc: "Calendar month of the trade date (1–12), for monthly seasonality cuts.",
    valueType: "number",
    unit: "count",
    sql: "f.month",
    groupable: true,
    library: [{ kind: "indicator", slug: "seasonality-chart" }],
  },
  {
    kind: "field",
    name: "year",
    title: "Year",
    doc: "Calendar year of the trade date. Grouping by year is the manual stability check.",
    valueType: "number",
    unit: "count",
    sql: "f.year",
    groupable: true,
  },
  {
    kind: "field",
    name: "rangePct",
    title: "Session range %",
    doc: "Session high-to-low range as a percent of the session's open.",
    valueType: "number",
    unit: "%",
    sql: "f.range_pct",
  },
  {
    kind: "field",
    name: "retOcPct",
    title: "Open→close return %",
    doc: "Session return from open to close, in percent (signed).",
    valueType: "number",
    unit: "%",
    sql: "f.ret_oc_pct",
    library: [{ kind: "concept", slug: "session-open-close-behaviors" }],
  },
  {
    kind: "field",
    name: "green",
    title: "Green session",
    doc: "True when the session closed above its open.",
    valueType: "boolean",
    sql: "f.green",
    groupable: true,
    library: [{ kind: "indicator", slug: "session-streaks" }],
  },
  {
    kind: "field",
    name: "gapPct",
    title: "Gap %",
    doc: "Opening gap versus the prior session's close, in percent (signed; positive = gapped up). NULL on roll days: a gap across a futures roll is a roll, not a gap.",
    valueType: "number",
    unit: "%",
    sql: "f.gap_pct",
    examples: ["gapFill WHERE gapPct BETWEEN 0.2% AND 0.6%"],
    library: [{ kind: "concept", slug: "gap-fill" }],
  },
  {
    kind: "field",
    name: "absGapPct",
    title: "Absolute gap %",
    doc: "Absolute size of the opening gap in percent, direction ignored.",
    valueType: "number",
    unit: "%",
    sql: "f.abs_gap_pct",
  },
  {
    kind: "field",
    name: "gapDir",
    title: "Gap direction",
    doc: "Direction of the opening gap: 'up', 'down', or 'none'.",
    valueType: "enum",
    enumValues: GAP_DIRS,
    sql: "f.gap_dir",
    groupable: true,
  },
  {
    kind: "field",
    name: "gapBucket",
    title: "Gap size bucket",
    doc: "Gap size bucketed for grouping: xs (<0.15%), s (0.15–0.3%), m (0.3–0.75%), l (0.75–1.5%), xl (≥1.5%).",
    valueType: "enum",
    enumValues: GAP_BUCKETS,
    sql: "f.gap_bucket",
    groupable: true,
  },
  {
    kind: "field",
    name: "gapFilled",
    title: "Gap filled",
    doc: "True when the session traded back to the prior session's close after gapping (the conventional fill).",
    valueType: "boolean",
    sql: "f.gap_filled",
    groupable: true,
    library: [
      { kind: "concept", slug: "gap-fill" },
      { kind: "indicator", slug: "session-gap-fill" },
    ],
  },
  {
    kind: "field",
    name: "gapFillMinutes",
    title: "Minutes to gap fill",
    doc: "Minutes from the session open to the gap fill (NULL when unfilled).",
    valueType: "number",
    unit: "minutes",
    sql: "f.gap_fill_min",
  },
  {
    kind: "field",
    name: "openPosInPrevRange",
    title: "Open position in prior range",
    doc: "Where the open printed inside the prior session's range: 0 = at prior low, 1 = at prior high; outside [0,1] = opened beyond the range.",
    valueType: "number",
    unit: "ratio",
    sql: "f.open_pos_prev_range",
    library: [{ kind: "indicator", slug: "session-levels-predictor" }],
  },
  {
    kind: "field",
    name: "openAbovePrevHigh",
    title: "Opened above prior high",
    doc: "True when the session opened above the prior session's high.",
    valueType: "boolean",
    sql: "f.open_above_prev_high",
    groupable: true,
  },
  {
    kind: "field",
    name: "openBelowPrevLow",
    title: "Opened below prior low",
    doc: "True when the session opened below the prior session's low.",
    valueType: "boolean",
    sql: "f.open_below_prev_low",
    groupable: true,
  },
  {
    kind: "field",
    name: "touchedPrevHigh",
    title: "Touched prior high",
    doc: "True when the session traded at or above the prior session's high at any point.",
    valueType: "boolean",
    sql: "f.touched_prev_high",
    groupable: true,
    library: [{ kind: "indicator", slug: "session-levels-predictor" }],
  },
  {
    kind: "field",
    name: "touchedPrevLow",
    title: "Touched prior low",
    doc: "True when the session traded at or below the prior session's low at any point.",
    valueType: "boolean",
    sql: "f.touched_prev_low",
    groupable: true,
  },
  {
    kind: "field",
    name: "touchPrevHighMinutes",
    title: "Minutes to prior high touch",
    doc: "Minutes from the open to the first touch of the prior high (NULL when untouched).",
    valueType: "number",
    unit: "minutes",
    sql: "f.touch_prev_high_min",
  },
  {
    kind: "field",
    name: "touchPrevLowMinutes",
    title: "Minutes to prior low touch",
    doc: "Minutes from the open to the first touch of the prior low (NULL when untouched).",
    valueType: "number",
    unit: "minutes",
    sql: "f.touch_prev_low_min",
  },
  {
    kind: "field",
    name: "closedAbovePrevHigh",
    title: "Closed above prior high",
    doc: "True when the session closed above the prior session's high.",
    valueType: "boolean",
    sql: "f.closed_above_prev_high",
    groupable: true,
  },
  {
    kind: "field",
    name: "closedBelowPrevLow",
    title: "Closed below prior low",
    doc: "True when the session closed below the prior session's low.",
    valueType: "boolean",
    sql: "f.closed_below_prev_low",
    groupable: true,
  },
  {
    kind: "field",
    name: "insideDay",
    title: "Inside session",
    doc: "True when the session's whole range sat inside the prior session's range.",
    valueType: "boolean",
    sql: "f.inside_day",
    groupable: true,
  },
  {
    kind: "field",
    name: "outsideDay",
    title: "Outside session",
    doc: "True when the session traded beyond both the prior session's high and low.",
    valueType: "boolean",
    sql: "f.outside_day",
    groupable: true,
  },
  {
    kind: "field",
    name: "nr4",
    title: "NR4",
    doc: "True when the session had the narrowest range of the last 4 sessions.",
    valueType: "boolean",
    sql: "f.nr4",
    groupable: true,
  },
  {
    kind: "field",
    name: "nr7",
    title: "NR7",
    doc: "True when the session had the narrowest range of the last 7 sessions.",
    valueType: "boolean",
    sql: "f.nr7",
    groupable: true,
  },
  {
    kind: "field",
    name: "bullEngulfing",
    title: "Bullish engulfing session",
    doc: "True when the session's body engulfed a prior red session's body (session-level candle).",
    valueType: "boolean",
    sql: "f.bull_engulf",
    groupable: true,
    library: [{ kind: "concept", slug: "engulfing-bar" }],
  },
  {
    kind: "field",
    name: "bearEngulfing",
    title: "Bearish engulfing session",
    doc: "True when the session's body engulfed a prior green session's body (session-level candle).",
    valueType: "boolean",
    sql: "f.bear_engulf",
    groupable: true,
    library: [{ kind: "concept", slug: "engulfing-bar" }],
  },
  {
    kind: "field",
    name: "doji",
    title: "Doji session",
    doc: "True when the session closed within 10% of its range from its open (session-level candle).",
    valueType: "boolean",
    sql: "f.doji",
    groupable: true,
    library: [{ kind: "concept", slug: "candlestick-patterns" }],
  },
  {
    kind: "field",
    name: "highTimeMinutes",
    title: "Minutes to session high",
    doc: "Minutes from the open to the first print of the session high.",
    valueType: "number",
    unit: "minutes",
    sql: "f.high_time_min",
    library: [{ kind: "concept", slug: "session-high-low-statistics" }],
  },
  {
    kind: "field",
    name: "lowTimeMinutes",
    title: "Minutes to session low",
    doc: "Minutes from the open to the first print of the session low.",
    valueType: "number",
    unit: "minutes",
    sql: "f.low_time_min",
    library: [{ kind: "concept", slug: "session-high-low-statistics" }],
  },
  {
    kind: "field",
    name: "highBeforeLow",
    title: "High before low",
    doc: "True when the session printed its high before its low.",
    valueType: "boolean",
    sql: "f.high_before_low",
    groupable: true,
  },
  {
    kind: "field",
    name: "atrPct",
    title: "ATR(14) %",
    doc: "Prior 14-session average true range as a percent of the prior close: the session's volatility context, known before the open.",
    valueType: "number",
    unit: "%",
    sql: "f.atr14_pct",
  },
  {
    kind: "field",
    name: "rangeVsAtr",
    title: "Range vs ATR",
    doc: "Session range divided by the prior ATR(14): how big the session was against its own recent volatility.",
    valueType: "number",
    unit: "ratio",
    sql: "f.range_vs_atr",
  },
  {
    kind: "field",
    name: "volumeVsAvg20",
    title: "Volume vs 20-session average",
    doc: "Session volume divided by the prior 20-session average volume.",
    valueType: "number",
    unit: "ratio",
    sql: "f.vol_vs_avg20",
  },
  {
    kind: "field",
    name: "prevGreenStreak",
    title: "Prior green streak",
    doc: "How many consecutive green sessions ended immediately before this one (0 when the prior session was red).",
    valueType: "number",
    unit: "count",
    sql: "f.prev_green_streak",
    library: [{ kind: "indicator", slug: "session-streaks" }],
  },
  {
    kind: "field",
    name: "prevRedStreak",
    title: "Prior red streak",
    doc: "How many consecutive red sessions ended immediately before this one.",
    valueType: "number",
    unit: "count",
    sql: "f.prev_red_streak",
  },
  {
    kind: "field",
    name: "prevDayGreen",
    title: "Prior session green",
    doc: "True when the prior session closed green.",
    valueType: "boolean",
    sql: "f.prev_day_green",
    groupable: true,
  },
  {
    kind: "field",
    name: "prevInsideDay",
    title: "Prior session was inside",
    doc: "True when the PRIOR session's range sat inside the range before it: conditioning today on yesterday's compression, known at the open.",
    valueType: "boolean",
    sql: "f.prev_inside_day",
    groupable: true,
    examples: ["closeGreen WHERE prevInsideDay", "orbBreak(15m) WHERE prevInsideDay"],
  },
  {
    kind: "field",
    name: "prevNr7",
    title: "Prior session was NR7",
    doc: "True when the PRIOR session had the narrowest range of its trailing 7: the classic day-after-compression setup, known at the open.",
    valueType: "boolean",
    sql: "f.prev_nr7",
    groupable: true,
    examples: ["hit(rangeVsAtr, gte, 1.5) WHERE prevNr7"],
  },
  {
    kind: "field",
    name: "prevDoji",
    title: "Prior session was a doji",
    doc: "True when the PRIOR session closed within 10% of its range from its open, known at the open.",
    valueType: "boolean",
    sql: "f.prev_doji",
    groupable: true,
    library: [{ kind: "concept", slug: "candlestick-patterns" }],
  },
  {
    kind: "field",
    name: "nextRangePct",
    title: "Next session range %",
    doc: "The NEXT session's high-to-low range as a percent of its open. As an outcome via hit(), this is the day-after expansion question: hit(nextRangePct, gte, x) WHERE nr7.",
    valueType: "number",
    unit: "%",
    sql: "f.next_range_pct",
    examples: ["hit(nextRangePct, gte, 1.5) WHERE nr7"],
  },
  {
    kind: "field",
    name: "nextRangeVsAtr",
    title: "Next session range vs ATR",
    doc: "The NEXT session's range divided by ITS prior ATR(14): day-after expansion in volatility-adjusted units.",
    valueType: "number",
    unit: "ratio",
    sql: "f.next_range_vs_atr",
    examples: ["hit(nextRangeVsAtr, gte, 1.5) WHERE nr7 AND insideDay"],
  },
  {
    kind: "field",
    name: "rollDay",
    title: "Futures roll day",
    doc: "True when the continuous futures series changed front contract on this session. Gap features are NULL on roll days; exclude or isolate them explicitly with this field.",
    valueType: "boolean",
    sql: "f.is_roll_day",
    groupable: true,
  },
  {
    kind: "field",
    name: "halfDay",
    title: "Half day",
    doc: "True when the exchange closed early on this session (holiday-adjacent schedules).",
    valueType: "boolean",
    sql: "f.is_half_day",
    groupable: true,
  },
  {
    kind: "field",
    name: "fvgAbove",
    title: "Unfilled FVG above",
    doc: "True when an unfilled session-level fair value gap sat entirely above the open at session start (formed on prior sessions: no lookahead).",
    valueType: "boolean",
    sql: "f.fvg_above",
    groupable: true,
    library: [{ kind: "indicator", slug: "fvg-sessions" }],
  },
  {
    kind: "field",
    name: "fvgBelow",
    title: "Unfilled FVG below",
    doc: "True when an unfilled session-level fair value gap sat entirely below the open at session start (formed on prior sessions: no lookahead).",
    valueType: "boolean",
    sql: "f.fvg_below",
    groupable: true,
    library: [{ kind: "indicator", slug: "fvg-sessions" }],
  },
  {
    kind: "field",
    name: "ibBreakType",
    title: "Initial-balance break type",
    doc: "How the session resolved its initial balance: 'none', 'single_up', 'single_down', or 'double' (both sides broken).",
    valueType: "enum",
    enumValues: IB_BREAKS,
    sql: "f.ib_break",
    groupable: true,
    library: [
      { kind: "concept", slug: "initial-balance" },
      { kind: "indicator", slug: "initial-balance-breakout-signals" },
    ],
  },
];
